#based on https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8.0.392+8
      - name: Build with Maven
        env:
          DISPLAY: ":99.0"
        run: xvfb-run --auto-servernum mvn -B package jacoco:report --file pom.xml

